apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: redis-web
  # labels so that we can bind a Service to this Pod
  labels:
    app: redis-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis-web
  template:
    metadata:
      labels:
        app: redis-web
    spec:
      containers:
      - name: redis-web
        image: cheungtom/redis-web:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "500m" #half the CPU free: 0.5 Core
            memory: "256Mi"
          limits:
            cpu: "1000m" #max 1.0 Core
            memory: "512Mi"
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
